default: &default
  adapter: postgresql
  encoding: utf-8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: 15

development:
  <<: *default
  database: upimages_development

test:
  <<: *default
  database: upimages_test

production:
  <<: *default
  database: upimages_production
  username: upimages
  password: <%= ENV['UPIMAGES_DATABASE_PASSWORD'] %>